# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-10 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal', '0002_auto_20170510_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='running',
            field=models.BooleanField(default=True),
        ),
    ]
