# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-11 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal', '0003_auto_20170510_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='running',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='position',
            field=models.CharField(choices=[('Representative', 'Representative'), ('Senator', 'Senator'), ('Other', 'Other')], max_length=200),
        ),
    ]
