# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal', '0004_auto_20170511_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='term_end',
            field=models.DateField(blank=True, null=True, verbose_name=b'Term End'),
        ),
    ]
