# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal', '0006_auto_20170606_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='facebook_text',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='tweet_text',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='reasons_to_keep',
            field=models.TextField(blank=True, null=True, verbose_name='Reasons to Keep/Elect'),
        ),
    ]
