# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal', '0007_auto_20170608_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('posted', models.BooleanField(default=True)),
                ('date_to_post', models.DateTimeField(blank=True, null=True, verbose_name='date to post')),
                ('tweet_text', models.CharField(blank=True, max_length=135, null=True)),
                ('facebook_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['active', 'posted', '-date_to_post'],
            },
        ),
    ]
