# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal', '0009_auto_20170613_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='district',
            field=models.CharField(default=b'House', max_length=16),
        ),
    ]
