# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal', '0010_auto_20170615_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='type',
            field=models.CharField(choices=[('H', 'House'), ('S', 'Senate')], default=b'H', max_length=2),
        ),
    ]
