# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal', '0012_auto_20170615_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='district',
            field=models.IntegerField(),
        ),
    ]
