# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 02:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('federal', '0013_auto_20170615_0148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reasons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('O', 'Vote Out'), ('I', 'Keep In')], max_length=4)),
                ('reason_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='reasons',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='federal.Reasons'),
        ),
    ]
