# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal', '0014_auto_20170620_0201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reasons',
            options={'verbose_name_plural': 'reasons'},
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='reasons',
        ),
        migrations.AddField(
            model_name='candidate',
            name='reasons',
            field=models.ManyToManyField(to='federal.Reasons'),
        ),
    ]
