# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal', '0015_auto_20170620_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='reasons',
            field=models.ManyToManyField(blank=True, null=True, to='federal.Reasons'),
        ),
    ]
