# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 03:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('federal', '0016_auto_20170620_0305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='reasons_to_keep',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='reasons_to_vote_out',
        ),
    ]
