# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal', '0018_auto_20170620_2011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unitedstatesmap',
            options={'verbose_name': 'US Map Coordinates', 'verbose_name_plural': 'US Map Coordinates'},
        ),
        migrations.AddField(
            model_name='reasons',
            name='reason_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reasons',
            name='reason_text',
            field=models.TextField(),
        ),
    ]
